# Generated by Django 4.2 on 2025-11-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specializtion', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='doctors/')),
                ('available_days', models.CharField(max_length=50)),
                ('available_time', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='userdata',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
