# Generated by Django 4.2 on 2025-11-04 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_doctor_alter_userdata_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='specializtion',
            new_name='specialization',
        ),
    ]
