# Generated by Django 4.2 on 2025-11-06 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_doctor_available_days_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='edbiography',
            new_name='biography',
        ),
    ]
