# Generated by Django 4.2 on 2025-11-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_edbiography_doctor_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
